export { PrismaClient } from '@prisma/client';
export * as Prisma from '@prisma/client';
export {
  // Enums
  Role,
  PermissionAction,
  AccountProvider,
  OAuthProvider,
  AuditAction,
  SessionStatus,
  DeviceType,
  LoginMethod,
  LoginStatus,
  CourseStatus,
  CourseLevel,
  CourseVisibility,
  CourseReviewStatus,
  CategoryStatus,
  CategoryVisibility,
  SubjectStatus,
  LessonType,
  ChapterStatus,
  ChapterVisibility,
  LessonStatus,
  LessonVisibility,
  VideoSource,
  VideoQuality,
  EnrollmentStatus,
  ProgressStatus,
  ResourceCategoryType,
  MeetingStatus,
  AttendanceStatus,
  BookingStatusName,
  RecurrenceType,
  ScheduleStatus,
  EventType,
  ExamType,
  QuestionType,
  DifficultyLevel,
  AttemptStatus,
  AssignmentType,
  SubmissionStatus,
  FileKind,
  StorageProvider,
  MessageType,
  MessageStatus,
  NotificationType,
  NotificationChannel,
  NotificationStatus,
  PaymentMethod,
  PaymentStatus,
  InvoiceStatus,
  SubscriptionStatus,
  CouponType,
  DiscountType,
  ReportType,
  ReportFormat,
  ReportStatus,
  CertificateStatus,
  SystemLogLevel,
  ErrorSeverity,
  ErrorStatus,
} from '@prisma/client';
export type {
  // Model types
  User,
  UserProfile,
  Roles,
  Permission,
  RolePermission,
  Teacher,
  Student,
  Admin,
  Moderator,
  Account,
  Session,
  RefreshToken,
  EmailVerificationToken,
  PasswordResetToken,
  Device,
  LoginHistory,
  Category,
  SubCategory,
  Subject,
  Course,
  CourseMedia,
  CourseReview,
  CourseAnalytics,
  CourseTeacher,
  CourseStudent,
  CourseChapter,
  Lesson,
  LessonVideo,
  LessonPDF,
  LessonAttachment,
  LessonResource,
  CourseResource,
  LessonProgress,
  ChapterProgress,
  EnrollmentActivity,
  ZoomMeeting,
  MeetingSchedule,
  MeetingAttendance,
  MeetingRecording,
  MeetingFeedback,
  TeacherAvailability,
  Booking,
  BookingStatus,
  BookingHistory,
  Reschedule,
  Event,
  Schedule,
  TeacherSchedule,
  StudentSchedule,
  Exam,
  ExamSection,
  Question,
  QuestionChoice,
  StudentAnswer,
  ExamAttempt,
  ExamResult,
  QuestionBank,
  ExamStatistics,
  Assignment,
  AssignmentFile,
  AssignmentSubmission,
  SubmissionGrade,
  SubmissionFeedback,
  Upload,
  Image,
  Video,
  Document,
  CloudStorage,
  Chat,
  ConversationMember,
  Message,
  MessageAttachment,
  Notification,
  NotificationTemplate,
  EmailNotification,
  PushNotification,
  SMSNotification,
  Certificate,
  CertificateTemplate,
  CertificateDownload,
  Payment,
  Invoice,
  Subscription,
  Coupon,
  DiscountCode,
  StudentReport,
  TeacherReport,
  AttendanceReport,
  RevenueReport,
  LessonFeedback,
  TeacherRating,
  CourseRating,
  PlatformFeedback,
  AuditLog,
  ActivityLog,
  SystemLog,
  ErrorLog,
  GeneralSettings,
  SecuritySettings,
  StorageSettings,
  EmailSettings,
  ZoomSettings,
  ThemeSettings,
} from '@prisma/client';

import { PrismaClient } from '@prisma/client';

const globalForPrisma = globalThis as unknown as { prisma: PrismaClient | undefined };

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    log: process.env.NODE_ENV === 'development' ? ['query', 'error', 'warn'] : ['error'],
  });

if (process.env.NODE_ENV !== 'production') {
  globalForPrisma.prisma = prisma;
}

export default prisma;
